language: generic
sudo: required

services:
  - docker

before_install: 
  - docker build -t ottter/docker-multi -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ottter/docker-multi npm test
