language: generic
sudo: required

services:
  - docker

before_install: 
  - docker build -t ottter/docker-multi -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ottter/docker-multi npm test

after_success:
  - docker build -t ottter/docker-multi-client -f ./client
  - docker build -t ottter/docker-multi-nginx  -f ./nginx
  - docker build -t ottter/docker-multi-server -f ./server
  - docker build -t ottter/docker-multi-worker -f ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push ottter/multi-client
  - docker push ottter/multi-nginx
  - docker push ottter/multi-server
  - docker push ottter/multi-worker
